spring:
  application:
    name: service-api-gateway
  cloud:
    gateway:
      routes:
        - id: app-authors-route
          uri: lb://service-app-authors
          predicates:
            - Path=/authors/**
