spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-app-authors
          uri: lb://service-app-authors
          predicates:
            - Path=/authors/**
            - Path=/authors/**

        - id: service-app-books
          uri: lb://service-app-books
          predicates:
            - Path=/books/**
            - Path=/authors/**
